/* NOTE: This code was generated by chatgpt */
export function replaceVariables(
  text: string,
  variables: Record<string, string | number>
) {
  var replacedText = ''
  var codeBlockMode = false
  var variableBuffer = ''

  var i = 0
  while (i < text.length) {
    if (text[i] === '`' && text.slice(i, i + 3) === '```') {
      codeBlockMode = !codeBlockMode
      replacedText += text.slice(i, i + 3)
      i += 3
      continue
    }

    if (codeBlockMode) {
      replacedText += text[i]
      i++
      continue
    }

    if (text[i] === '{' && text[i + 1] === '{') {
      var j = i + 2
      while (
        j < text.length &&
        !(text[j] === '}' && text[j + 1] === '}')
      ) {
        variableBuffer += text[j]
        j++
      }

      var variable = variableBuffer.trim()
      var replacement =
        variables[variable] || '{{' + variable + '}}'
      replacedText += replacement

      i = j + 2 // Skip over the closing "}}"
      variableBuffer = ''
    } else {
      replacedText += text[i]
      i++
    }
  }

  return replacedText
}
